### ISSUE TITLE
这里的例子并没有说服力

### ISSUE THREAD

**Issue by bravekingzhang** [xujinyang/ReduxAndroid#1]
> 这个思想在我有限的开发经验中占很重要的地位。举个例子:
> 1.在一个通知列表里面，标记一个通知已读，发生已读请求后，要刷新UI，你会怎么做？
> 可能你会在发送一个已读请求后，直接控制当前的ViewHolder显示为已读样式，这样有问题么？没有问题！
> 2.这个时候再加个需求，要更新外部一个页面当前的未读通知数目。
> 是不是有点懵逼，当然大神还是有方法，获取当前的未读数目，减去刚才标记已读的一个。ok 又解决了！
> 3.再加一个需求，当未读通知数目少于5个的时候，显示一个清空的按钮。
> 这个时候，你会发现，按照上面的思路，会写出很多零碎的逻辑，随着功能的增加，复杂度激增和可维护性降低,但是又隐约的感觉到之间共通的联系，那就是：都是经过一些操作之后，需要刷新UI，而UI显示的依据是上面？那就是数据。
> 那么我们换个思路再来推理一遍。
> 1.在一个通知列表里面，标记一个通知已读，发生已读请求后，要刷新UI，你会怎么做？
> 发送已读请求之后，修改通知list中对于的item已读状态为true,然后调用listAdapter.notifyDataSetChanged（）,更具最新的UI。
> 2.这个时候再加个需求，要更新外部一个页面当前的未读通知数目。
> 接着上面，改变list中的item已读状态之后，那么当前的未读通知数目就立马获取到了，这个时候把这个数目发送给外部的UI，让它更具这个数目刷新UI。
> 3.再加一个需求，当未读通知数目少于5个的时候，显示一个清空的按钮。
> 同样，改变list中的item已读状态之后,如果未读数目少于5个，显示出清空按钮，这就是个if else的问题。
> 感受一下，复杂度是不是立马降到了线性范围，原来三个或者更多的方法，现在就变成了改变数据，刷新UI这俩步。
## 

> 直接控制当前的ViewHolder显示为已读样式，到
> 
> notifyDataSetChanged

 **这里只不过是从遇到什么情况，动态的加什么逻辑，转变到  
先把可能的数据对应UI逻辑写好 ，等到data不同去刷新**

个人感觉，即便是不了解Redux思想的人 ，可能也会选择第二种吧，那么，what is Redux ，可能你并没有哦举一个恰当的例子。

**Comment by xujinyang** [comment]
哦，这是我写的问题，这个例子只是说明“所有的UI刷新都交给数据来控制”这个思想,what is Redux ？这个请参考:http://cn.redux.js.org/index.html和http://div.io/topic/1309
